version: "2"

run:
  concurrency: 4
  timeout: 5m

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/vigo/leech

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - revive
    - noctx
    - bodyclose
    - errorlint
    - nilerr
    - copyloopvar
    - intrange
    - perfsprint
    - unconvert
    - unparam
    - wastedassign
    - errname
    - canonicalheader
    - fatcontext

  settings:
    revive:
      enable-all-rules: true
      rules:
        - name: package-comments
          disabled: true
        - name: unused-parameter
          arguments:
            - allow-regex: "^_"
        - name: add-constant
          arguments:
            - max-lit-count: "3"
              allow-strs: '"","err"'
              allow-ints: "0,1,2,5,10,30,100"
              allow-floats: "1.0"
        - name: cognitive-complexity
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: function-length
          arguments: [75, 0]
        - name: line-length-limit
          arguments: [120]
        - name: deep-exit
          disabled: true

    govet:
      enable:
        - shadow

    perfsprint:
      strconcat: false

  exclusions:
    warn-unused: true
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - path: _test\.go
        linters:
          - bodyclose
          - errcheck
          - gosec
          - noctx
          - unparam
          - revive
